[project]
name = "ospo.wisc.edu"
version = "0.1.0"
description = "Website for the University of Wisconsin's Open Source Program Office"
authors = ["Matthew Feickert <matthew.feickert@wisc.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]
[tasks.install]
description = "Install the Ruby Gem dependencies"
# Need to use '--user-install' as using pixi instead of rbenv
cmd = """
gem install --user-install bundle && \
bundle install
"""

[tasks.check]
description = "Perform validation checks"
cmd = "bundle exec rake check"

[tasks.build]
description = "Statically build the site"
cmd = "bundle exec rake build"

[tasks.serve]
description = "Build the site and serve it live"
cmd = "bundle exec rake serve"

[tasks.clean]
description = "Clean up and remove artifacts generated during the build"
cmd = "bundle exec rake clean"

[tasks.clobber]
description = "Clean everything generated during the build"
cmd = "bundle exec rake clobber"

[tasks.start]
description = "Install the Ruby Gem dependencies and build and serve the site"
depends-on = ["install", "serve"]

[dependencies]
ruby = ">=3.3.3,<4"
compilers = ">=1.7.0,<2"
imagemagick = ">=7.1.1_36,<8"
